name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/primeira-pipeline-gta:v${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/primeira-pipeline-gta:latest
        
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configuration of context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_KUBECONFIG }}

      - name: Execution the manifest
        uses: Azure/k8s-deploy@v5
        with:
          namespace: default
          manifests: |
              ./k8s/deployment.yaml
          images: ${{ secrets.DOCKERHUB_USERNAME }}/primeira-pipeline-gta:v${{ github.run_number }}


